/**
 * API service for communicating with the backend
 */

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000/api/v1';

export interface ArchiveResponse {
  id: string;
  title: string;
  media_types: ('image' | 'video' | 'audio' | 'document')[];
  dates?: string[];
  tags?: string[];
  description?: string;
  // summary is hidden - generated by AI but not exposed to users
  file_uris: string[];
  storage_paths?: string[];
  genai_file_ids?: string[];
  created_at: string;
  updated_at?: string;
  similarity?: number;
}

export interface CreateArchiveRequest {
  files: File[];
  title: string;
  media_types: ('image' | 'video' | 'audio' | 'document')[];
  tags?: string[];
  description?: string;
  dates?: string[];
}

export interface UpdateArchiveRequest {
  title?: string;
  tags?: string[];
  description?: string;
  dates?: string[];
}

export interface MetadataSuggestions {
  title: string;
  tags: string[];
  description: string;
}

export interface AISearchRequest {
  query: string;
}

export interface AISearchResponse {
  response_type: 'results' | 'message';  // Type of response
  archives: ArchiveResponse[];  // Empty array if response_type='message'
  total: number;
  query: string;
  message: string | null;  // Text message for non-search intents, null for results
}

export interface AISearchStreamUpdate {
  type: 'query_received' | 'searching' | 'results' | 'message' | 'done' | 'complete' | 'error';
  query?: string;
  timestamp?: string;
  thread_id?: string;
  content?: string | ArchiveResponse[];
  archives?: ArchiveResponse[];
  total?: number;
  message?: string;
  response_type?: 'results' | 'message';  // In 'complete' event
}

/**
 * Generate metadata suggestions from uploaded files
 */
export async function generateMetadata(
  files: File[],
  mediaTypes: ('image' | 'video' | 'audio' | 'document')[]
): Promise<MetadataSuggestions> {
  try {
    const formData = new FormData();

    // Append files
    files.forEach((file) => {
      formData.append('files', file);
    });

    // Append media types
    formData.append('media_types', mediaTypes.join(','));

    const response = await fetch(`${API_BASE_URL}/archives/generate-metadata`, {
      method: 'POST',
      body: formData,
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(
        errorData.detail || `Failed to generate metadata: ${response.statusText}`
      );
    }

    return await response.json();
  } catch (error) {
    if (error instanceof Error) {
      throw error;
    }
    throw new Error('Unknown error occurred while generating metadata');
  }
}

/**
 * Create a new archive by uploading files and analyzing content
 */
export async function createArchive(
  request: CreateArchiveRequest
): Promise<ArchiveResponse> {
  try {
    const formData = new FormData();

    // Append files
    request.files.forEach((file) => {
      formData.append('files', file);
    });

    // Append form fields
    formData.append('title', request.title);
    formData.append('media_types', request.media_types.join(','));
    
    if (request.tags && request.tags.length > 0) {
      formData.append('tags', request.tags.join(','));
    }
    
    if (request.description) {
      formData.append('description', request.description);
    }
    
    if (request.dates && request.dates.length > 0) {
      formData.append('dates', request.dates.join(','));
    }

    const response = await fetch(`${API_BASE_URL}/archives`, {
      method: 'POST',
      body: formData,
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(
        errorData.detail || `Failed to create archive: ${response.statusText}`
      );
    }

    return await response.json();
  } catch (error) {
    if (error instanceof Error) {
      throw error;
    }
    throw new Error('Unknown error occurred while creating archive');
  }
}

/**
 * Get all archives
 */
export async function getArchives(): Promise<ArchiveResponse[]> {
  try {
    const response = await fetch(`${API_BASE_URL}/archives`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      },
    });

    if (!response.ok) {
      throw new Error(`Failed to fetch archives: ${response.statusText}`);
    }

    return await response.json();
  } catch (error) {
    if (error instanceof Error) {
      throw error;
    }
    throw new Error('Unknown error occurred while fetching archives');
  }
}

/**
 * Delete an archive
 */
export async function deleteArchive(id: string): Promise<void> {
  try {
    const response = await fetch(`${API_BASE_URL}/archives/${id}`, {
      method: 'DELETE',
    });

    if (!response.ok) {
      throw new Error(`Failed to delete archive: ${response.statusText}`);
    }
  } catch (error) {
    if (error instanceof Error) {
      throw error;
    }
    throw new Error('Unknown error occurred while deleting archive');
  }
}

/**
 * Update an archive
 * When user edits their archive, the AI summary is automatically regenerated
 * to reflect the updated information (but remains hidden from user)
 */
export async function updateArchive(
  id: string,
  request: UpdateArchiveRequest
): Promise<ArchiveResponse> {
  try {
    const response = await fetch(`${API_BASE_URL}/archives/${id}`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(request),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(
        errorData.detail || `Failed to update archive: ${response.statusText}`
      );
    }

    return await response.json();
  } catch (error) {
    if (error instanceof Error) {
      throw error;
    }
    throw new Error('Unknown error occurred while updating archive');
  }
}

/**
 * AI-powered search for archives using LangChain agent
 */
export async function aiSearchArchives(query: string): Promise<AISearchResponse> {
  try {
    const response = await fetch(`${API_BASE_URL}/ai-search`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ query }),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(
        errorData.detail || `AI search failed: ${response.statusText}`
      );
    }

    return await response.json();
  } catch (error) {
    if (error instanceof Error) {
      throw error;
    }
    throw new Error('Unknown error occurred during AI search');
  }
}

/**
 * AI-powered search with streaming support (Server-Sent Events)
 * 
 * @param query - The search query
 * @param onUpdate - Callback for each streaming update
 * @returns Promise that resolves when streaming is complete
 */
export async function aiSearchArchivesStream(
  query: string,
  onUpdate: (update: AISearchStreamUpdate) => void
): Promise<void> {
  try {
    const response = await fetch(`${API_BASE_URL}/ai-search/stream`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ query }),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(
        errorData.detail || `AI search streaming failed: ${response.statusText}`
      );
    }

    const reader = response.body?.getReader();
    if (!reader) {
      throw new Error('Response body is not readable');
    }

    const decoder = new TextDecoder();
    let buffer = '';

    while (true) {
      const { done, value } = await reader.read();
      
      if (done) {
        break;
      }

      // Decode the chunk and add to buffer
      buffer += decoder.decode(value, { stream: true });

      // Process complete SSE messages
      const lines = buffer.split('\n\n');
      buffer = lines.pop() || ''; // Keep incomplete message in buffer

      for (const line of lines) {
        if (line.startsWith('data: ')) {
          const data = line.slice(6); // Remove 'data: ' prefix
          try {
            const update: AISearchStreamUpdate = JSON.parse(data);
            onUpdate(update);
            
            // Stop if we receive done or error
            if (update.type === 'done' || update.type === 'error') {
              return;
            }
          } catch (e) {
            console.error('Failed to parse SSE data:', e);
          }
        }
      }
    }
  } catch (error) {
    if (error instanceof Error) {
      throw error;
    }
    throw new Error('Unknown error occurred during AI search streaming');
  }
}

/**
 * Get a downloadable URL for a specific file in an archive
 * 
 * @param archiveId - The ID of the archive
 * @param fileIndex - The index of the file in the archive's storage_paths (0-based)
 * @returns Promise with the download URL and storage path
 */
export async function getArchiveFileDownloadUrl(
  archiveId: string,
  fileIndex: number
): Promise<{ url: string; storage_path: string }> {
  try {
    const response = await fetch(
      `${API_BASE_URL}/archives/${archiveId}/download/${fileIndex}`,
      {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      }
    );

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(
        errorData.detail || `Failed to get download URL: ${response.statusText}`
      );
    }

    return await response.json();
  } catch (error) {
    if (error instanceof Error) {
      throw error;
    }
    throw new Error('Unknown error occurred while getting download URL');
  }
}
